### ISSUE TITLE
How can I change the map

### ISSUE THREAD

**Issue by nesrine1997** [brunoolivieri/gradys-simulations#16]
Hello sir, I downloaded a map from OpenStreetMap, then I downloaded osgearth so I can change it to an earth file I don't know how to do it exactly, I want to change the location of the node in the new map, please if you can help me with the steps how to change it or a tutorial link, or what requires exactly I will be so grateful.

**Comment by brunoolivieri** [comment]
Hi!

Did you changed the https://github.com/brunoolivieri/gradys-simulations/blob/e14092ffc632d4bd3551f92e88818063b43b098c/mobilityDrones-omnetpp.ini#L66 ?

**Comment by nesrine1997** [comment]
hi sir, sorry I didn't see your replay, no i didn't change it! should I change it before changing the map!
