### ISSUE TITLE
[ERROR] Framework can not work with submodule errors

### ISSUE THREAD

**Issue by LaplaceZhang** [brunoolivieri/gradys-simulations#17]
Hi, I installed this framework with Omnet + INET 4.2 on Ubuntu 20.04. I tried to build the **mobilityDrones-omnetpp.ini** file but got the following error in return:

> cMatchExpression: Parse error in match expression: syntax error, unexpected STRINGLITERAL, expecting $end -- in module (inet::visualizer::StatisticCanvasVisualizer) mobilityDrones.visualizer.canvasVisualizer.statisticVisualizer (id=24), during network initialization

![Screenshot from 2022-09-09 21-24-24](https://user-images.githubusercontent.com/25606364/189437176-de2fbdc0-1a29-4103-9f7d-23d9eca6d24b.png)

Also, I noticed some `.ned` files report errors and all of them are caused by the `protocolGate` with description:

> wrong destination gate: submodule 'xxx' has no gate named 'protocolGate'

where `xxx` refers to module names, I looked through the code and found the `protocolGate` is defined in the `DroneMobility.ned` as an `inout` gate. I tried to import it, but the error remains. It would be appreciated and very helpful if you knew how to fix this issue. Thanks! :smiley:

**Comment by LaplaceZhang** [comment]
The reason why I failed to build this work is cause I was using OMNet 6.0. I tried OMNet 5.6.2 with INET 4.2.5, and it works! The `protocolGate` error remains, but it seems harmless and does not affect code running.

**Comment by Thlamz** [comment]
Unfortunately, I cannot figure out a way to hide that protocolGate error. It is a consequence of how we have structured our simulation, it is completely harmless!
