### ISSUE TITLE
missing sensors. 

### ISSUE THREAD

**Issue by thomoasis** [brunoolivieri/gradys-simulations#19]
Hello.  I tried changing the map and putting in the 8 sensors in different locations but they are not show up on the map except for 0.  I changed the coordinates in General and Config Wifi.  I also changed voo_ar.waypoints in Config Wifi and voo_sensor1.waypoints and voo_sensor2.waypoints.  Is there something I'm missing?  i am trying to run the Simple Configuration with a different map. 
![Map](https://user-images.githubusercontent.com/31631633/202961648-a1c357e0-9d10-4fba-bd99-1f4c6bebf4de.png)

**Comment by Thlamz** [comment]
Hello @thomoasis, are the sensors invisible but still simulated? With that I mean, are the drones still able to exchange messages with the invisible sensors?

There is a bug in the version that we use of OMNeT++ that prevents sensors lying in negative euclidean coordinates (-x or -y) from being rendered. A workaround that we have used is to shift the center of the scenario's camera so every sensor is positioned in positive euclidean coordinates. You can move the scenario's camera by changing the coordinateSystem.sceneLongitude and coordinateSystem.sceneLatitude parameters.

**Comment by thomoasis** [comment]
it worked!  thanks for the help.  I flipped it around and now it works.  thanks!

![mapfull](https://user-images.githubusercontent.com/31631633/204072939-b4214971-ae51-4704-a817-79a27df67d24.png)

**Comment by thomoasis** [comment]
thanks for the help! may have more questions soon!
